name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # - name: Install cosign
      #   if: github.event_name != 'pull_request'
      #   uses: sigstore/cosign-installer@v3.6.0
      #   with:
      #     cosign-release: 'v2.2.4' # optional   
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image for yelb-appserver
        run: docker build -t ghcr.io/${{ github.repository_owner }}/yelb-appserver:latest ./yelb-appserver
      - name: Build the Docker image for yelb-db
        run: docker build -t ghcr.io/${{ github.repository_owner }}/yelb-db:latest ./yelb-db
      - name: Build the Docker image for yelb-ui
        run: docker build -t ghcr.io/${{ github.repository_owner }}/yelb-ui:latest ./yelb-ui
      - name: Push the Docker images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/yelb-appserver:latest
          docker push ghcr.io/${{ github.repository_owner }}/yelb-db:latest
          docker push ghcr.io/${{ github.repository_owner }}/yelb-ui:latest   
